version: "3.8"

services:
  cube_api:
    image: cubejs/cube:latest
    platform: linux/amd64
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_router
      - cubestore_worker_1
    networks:
      - cube_network

  cube_refresh_worker:
    image: cubejs/cube:latest
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_router
      - cubestore_worker_1
    networks:
      - cube_network

  cubestore_router:
    image: cubejs/cubestore:v0.33.52
    platform: linux/amd64
    ports:
      - "3030:3030"
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_HTTP_BIND_ADDR=0.0.0.0
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    volumes:
      - .cubestore:/cube/data
    networks:
      - cube_network
   
  cubestore_worker_1:
    image: cubejs/cubestore:v0.33.52
    platform: linux/amd64
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router
    networks:
      - cube_network

networks:
  cube_network:
    driver: bridge